version: "3.3"
services:
  postgres_services:
    container_name: postgres_services
    image: postgres:12.14
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
    restart: on-failure